# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eef0897628823adf97b6158e89975e43c9bd6fec3a27dda6f8e1aa62f40e8a3d1579921e1429a4e249d4f6a4df590dadb2d37458e2bf628cfb5d9ece565c9fc

test:
  secret_key_base: 4fb1b417c371fd5ccd7d83f43bd4018ac33adef210cdc4121437518678c7d3d12465d5992d2ebc93449a21b01b23161e562947532bca735e222a11ab8557c038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
